// -*- C++ -*-
#ifndef SkimTree_H
#define SkimTree_H
#include "Math/LorentzVector.h"
#include "Math/GenVector/PtEtaPhiM4D.h"
#include "Math/Point3D.h"
#include "TMath.h"
#include "TBranch.h"
#include "TTree.h"
#include "TH1F.h"
#include "TFile.h"
#include "TBits.h"
#include <vector>
#include <unistd.h>
typedef ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<float> > LorentzVector;

// Generated with command: -t SkimTree -n tas -o st -c SkimTree -plv /hadoop/cms/store/user/usarica/Offshell_2L2Nu/Worker/output/DileptonEvents/SkimTrees/201006/AK4Jets_WithPUJetId_NoTightLeptonJetId_ParticleCleaned/PFMET_WithXY_WithJER_WithPartMomCorr_P4Preserved_ResolutionCorrected/2017/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14_ext1-v1_45_of_49_Nominal.root 

using namespace std;
class SkimTree {
private:
protected:
  unsigned int index;
  vector<float> *ak4jets_CEMF_;
  TBranch *ak4jets_CEMF_branch;
  bool ak4jets_CEMF_isLoaded;
  float ak4jets_HT_;
  TBranch *ak4jets_HT_branch;
  bool ak4jets_HT_isLoaded;
  vector<float> *ak4jets_NEMF_;
  TBranch *ak4jets_NEMF_branch;
  bool ak4jets_NEMF_isLoaded;
  vector<unsigned char> *ak4jets_btagWP_Bits_;
  TBranch *ak4jets_btagWP_Bits_branch;
  bool ak4jets_btagWP_Bits_isLoaded;
  vector<float> *ak4jets_eta_;
  TBranch *ak4jets_eta_branch;
  bool ak4jets_eta_isLoaded;
  vector<bool> *ak4jets_is_genMatched_;
  TBranch *ak4jets_is_genMatched_branch;
  bool ak4jets_is_genMatched_isLoaded;
  vector<bool> *ak4jets_is_genMatched_fullCone_;
  TBranch *ak4jets_is_genMatched_fullCone_branch;
  bool ak4jets_is_genMatched_fullCone_isLoaded;
  vector<float> *ak4jets_mass_;
  TBranch *ak4jets_mass_branch;
  bool ak4jets_mass_isLoaded;
  vector<float> *ak4jets_phi_;
  TBranch *ak4jets_phi_branch;
  bool ak4jets_phi_isLoaded;
  vector<float> *ak4jets_pt_;
  TBranch *ak4jets_pt_branch;
  bool ak4jets_pt_isLoaded;
  vector<float> *ak8jets_eta_;
  TBranch *ak8jets_eta_branch;
  bool ak8jets_eta_isLoaded;
  vector<float> *ak8jets_mass_;
  TBranch *ak8jets_mass_branch;
  bool ak8jets_mass_isLoaded;
  vector<float> *ak8jets_phi_;
  TBranch *ak8jets_phi_branch;
  bool ak8jets_phi_isLoaded;
  vector<float> *ak8jets_pt_;
  TBranch *ak8jets_pt_branch;
  bool ak8jets_pt_isLoaded;
  float dPhi_pTboson_pTmiss_;
  TBranch *dPhi_pTboson_pTmiss_branch;
  bool dPhi_pTboson_pTmiss_isLoaded;
  float dPhi_pTbosonjets_pTmiss_;
  TBranch *dPhi_pTbosonjets_pTmiss_branch;
  bool dPhi_pTbosonjets_pTmiss_isLoaded;
  float dilepton_eta_;
  TBranch *dilepton_eta_branch;
  bool dilepton_eta_isLoaded;
  int dilepton_id_;
  TBranch *dilepton_id_branch;
  bool dilepton_id_isLoaded;
  float dilepton_mass_;
  TBranch *dilepton_mass_branch;
  bool dilepton_mass_isLoaded;
  float dilepton_phi_;
  TBranch *dilepton_phi_branch;
  bool dilepton_phi_isLoaded;
  float dilepton_pt_;
  TBranch *dilepton_pt_branch;
  bool dilepton_pt_isLoaded;
  vector<float> *electrons_full5x5_r9_;
  TBranch *electrons_full5x5_r9_branch;
  bool electrons_full5x5_r9_isLoaded;
  vector<float> *electrons_full5x5_sigmaIEtaIEta_;
  TBranch *electrons_full5x5_sigmaIEtaIEta_branch;
  bool electrons_full5x5_sigmaIEtaIEta_isLoaded;
  vector<float> *electrons_full5x5_sigmaIPhiIPhi_;
  TBranch *electrons_full5x5_sigmaIPhiIPhi_branch;
  bool electrons_full5x5_sigmaIPhiIPhi_isLoaded;
  vector<float> *electrons_seedTime_;
  TBranch *electrons_seedTime_branch;
  bool electrons_seedTime_isLoaded;
  float event_mTZZ_;
  TBranch *event_mTZZ_branch;
  bool event_mTZZ_isLoaded;
  float event_mZZ_;
  TBranch *event_mZZ_branch;
  bool event_mZZ_isLoaded;
  float event_mllg_;
  TBranch *event_mllg_branch;
  bool event_mllg_isLoaded;
  unsigned int event_n_ak4jets_pt20_;
  TBranch *event_n_ak4jets_pt20_branch;
  bool event_n_ak4jets_pt20_isLoaded;
  unsigned int event_n_ak4jets_pt20_btagged_loose_;
  TBranch *event_n_ak4jets_pt20_btagged_loose_branch;
  bool event_n_ak4jets_pt20_btagged_loose_isLoaded;
  unsigned int event_n_ak4jets_pt20_btagged_medium_;
  TBranch *event_n_ak4jets_pt20_btagged_medium_branch;
  bool event_n_ak4jets_pt20_btagged_medium_isLoaded;
  unsigned int event_n_ak4jets_pt30_;
  TBranch *event_n_ak4jets_pt30_branch;
  bool event_n_ak4jets_pt30_isLoaded;
  unsigned int event_n_ak4jets_pt30_btagged_loose_;
  TBranch *event_n_ak4jets_pt30_btagged_loose_branch;
  bool event_n_ak4jets_pt30_btagged_loose_isLoaded;
  unsigned int event_n_ak4jets_pt30_btagged_medium_;
  TBranch *event_n_ak4jets_pt30_btagged_medium_branch;
  bool event_n_ak4jets_pt30_btagged_medium_isLoaded;
  unsigned int event_n_vtxs_good_;
  TBranch *event_n_vtxs_good_branch;
  bool event_n_vtxs_good_isLoaded;
  float event_pTmiss_;
  TBranch *event_pTmiss_branch;
  bool event_pTmiss_isLoaded;
  bool event_pass_tightMETFilters_;
  TBranch *event_pass_tightMETFilters_branch;
  bool event_pass_tightMETFilters_isLoaded;
  float event_phimiss_;
  TBranch *event_phimiss_branch;
  bool event_phimiss_isLoaded;
  float event_wgt_;
  TBranch *event_wgt_branch;
  bool event_wgt_isLoaded;
  float event_wgt_SFs_;
  TBranch *event_wgt_SFs_branch;
  bool event_wgt_SFs_isLoaded;
  float event_wgt_SFs_PUJetId_;
  TBranch *event_wgt_SFs_PUJetId_branch;
  bool event_wgt_SFs_PUJetId_isLoaded;
  float event_wgt_SFs_btagging_;
  TBranch *event_wgt_SFs_btagging_branch;
  bool event_wgt_SFs_btagging_isLoaded;
  float event_wgt_SFs_electrons_;
  TBranch *event_wgt_SFs_electrons_branch;
  bool event_wgt_SFs_electrons_isLoaded;
  float event_wgt_SFs_muons_;
  TBranch *event_wgt_SFs_muons_branch;
  bool event_wgt_SFs_muons_isLoaded;
  float event_wgt_SFs_photons_;
  TBranch *event_wgt_SFs_photons_branch;
  bool event_wgt_SFs_photons_isLoaded;
  float event_wgt_adjustment_NNPDF30_;
  TBranch *event_wgt_adjustment_NNPDF30_branch;
  bool event_wgt_adjustment_NNPDF30_isLoaded;
  float event_wgt_triggers_;
  TBranch *event_wgt_triggers_branch;
  bool event_wgt_triggers_isLoaded;
  float event_wgt_triggers_Dilepton_;
  TBranch *event_wgt_triggers_Dilepton_branch;
  bool event_wgt_triggers_Dilepton_isLoaded;
  float event_wgt_triggers_PFHT_Control_;
  TBranch *event_wgt_triggers_PFHT_Control_branch;
  bool event_wgt_triggers_PFHT_Control_isLoaded;
  float event_wgt_triggers_SingleLepton_;
  TBranch *event_wgt_triggers_SingleLepton_branch;
  bool event_wgt_triggers_SingleLepton_isLoaded;
  float event_wgt_triggers_SinglePhoton_;
  TBranch *event_wgt_triggers_SinglePhoton_branch;
  bool event_wgt_triggers_SinglePhoton_isLoaded;
  float genmet_pTmiss_;
  TBranch *genmet_pTmiss_branch;
  bool genmet_pTmiss_isLoaded;
  float genmet_phimiss_;
  TBranch *genmet_phimiss_branch;
  bool genmet_phimiss_isLoaded;
  vector<float> *leptons_eff_;
  TBranch *leptons_eff_branch;
  bool leptons_eff_isLoaded;
  vector<float> *leptons_eff_DF_;
  TBranch *leptons_eff_DF_branch;
  bool leptons_eff_DF_isLoaded;
  vector<float> *leptons_eta_;
  TBranch *leptons_eta_branch;
  bool leptons_eta_isLoaded;
  vector<int> *leptons_id_;
  TBranch *leptons_id_branch;
  bool leptons_id_isLoaded;
  vector<bool> *leptons_is_TOmatched_SingleLepton_;
  TBranch *leptons_is_TOmatched_SingleLepton_branch;
  bool leptons_is_TOmatched_SingleLepton_isLoaded;
  vector<bool> *leptons_is_genMatched_prompt_;
  TBranch *leptons_is_genMatched_prompt_branch;
  bool leptons_is_genMatched_prompt_isLoaded;
  vector<float> *leptons_mass_;
  TBranch *leptons_mass_branch;
  bool leptons_mass_isLoaded;
  vector<float> *leptons_phi_;
  TBranch *leptons_phi_branch;
  bool leptons_phi_isLoaded;
  vector<float> *leptons_pt_;
  TBranch *leptons_pt_branch;
  bool leptons_pt_isLoaded;
  float min_abs_dPhi_pTj_pTmiss_;
  TBranch *min_abs_dPhi_pTj_pTmiss_branch;
  bool min_abs_dPhi_pTj_pTmiss_isLoaded;
  float pConst_JJQCD_SIG_ghg2_1_JHUGen_;
  TBranch *pConst_JJQCD_SIG_ghg2_1_JHUGen_branch;
  bool pConst_JJQCD_SIG_ghg2_1_JHUGen_isLoaded;
  float pConst_JJVBF_SIG_ghv1_1_JHUGen_;
  TBranch *pConst_JJVBF_SIG_ghv1_1_JHUGen_branch;
  bool pConst_JJVBF_SIG_ghv1_1_JHUGen_isLoaded;
  float p_JJQCD_SIG_ghg2_1_JHUGen_;
  TBranch *p_JJQCD_SIG_ghg2_1_JHUGen_branch;
  bool p_JJQCD_SIG_ghg2_1_JHUGen_isLoaded;
  float p_JJVBF_SIG_ghv1_1_JHUGen_;
  TBranch *p_JJVBF_SIG_ghv1_1_JHUGen_branch;
  bool p_JJVBF_SIG_ghv1_1_JHUGen_isLoaded;
  float p_JJVBF_SIG_ghv1_1_ghv1prime2_1E4_JHUGen_;
  TBranch *p_JJVBF_SIG_ghv1_1_ghv1prime2_1E4_JHUGen_branch;
  bool p_JJVBF_SIG_ghv1_1_ghv1prime2_1E4_JHUGen_isLoaded;
  float p_JJVBF_SIG_ghv1_1_ghv2_1_JHUGen_;
  TBranch *p_JJVBF_SIG_ghv1_1_ghv2_1_JHUGen_branch;
  bool p_JJVBF_SIG_ghv1_1_ghv2_1_JHUGen_isLoaded;
  float p_JJVBF_SIG_ghv1_1_ghv4_1_JHUGen_;
  TBranch *p_JJVBF_SIG_ghv1_1_ghv4_1_JHUGen_branch;
  bool p_JJVBF_SIG_ghv1_1_ghv4_1_JHUGen_isLoaded;
  float p_JJVBF_SIG_ghv1prime2_1E4_JHUGen_;
  TBranch *p_JJVBF_SIG_ghv1prime2_1E4_JHUGen_branch;
  bool p_JJVBF_SIG_ghv1prime2_1E4_JHUGen_isLoaded;
  float p_JJVBF_SIG_ghv2_1_JHUGen_;
  TBranch *p_JJVBF_SIG_ghv2_1_JHUGen_branch;
  bool p_JJVBF_SIG_ghv2_1_JHUGen_isLoaded;
  float p_JJVBF_SIG_ghv4_1_JHUGen_;
  TBranch *p_JJVBF_SIG_ghv4_1_JHUGen_branch;
  bool p_JJVBF_SIG_ghv4_1_JHUGen_isLoaded;
  float p_JJVBF_SIG_ghza1prime2_1E4_JHUGen_;
  TBranch *p_JJVBF_SIG_ghza1prime2_1E4_JHUGen_branch;
  bool p_JJVBF_SIG_ghza1prime2_1E4_JHUGen_isLoaded;
  float photon_MIPTotalEnergy_;
  TBranch *photon_MIPTotalEnergy_branch;
  bool photon_MIPTotalEnergy_isLoaded;
  float photon_eta_;
  TBranch *photon_eta_branch;
  bool photon_eta_isLoaded;
  float photon_full5x5_r9_;
  TBranch *photon_full5x5_r9_branch;
  bool photon_full5x5_r9_isLoaded;
  float photon_full5x5_sigmaIEtaIEta_;
  TBranch *photon_full5x5_sigmaIEtaIEta_branch;
  bool photon_full5x5_sigmaIEtaIEta_isLoaded;
  float photon_full5x5_sigmaIPhiIPhi_;
  TBranch *photon_full5x5_sigmaIPhiIPhi_branch;
  bool photon_full5x5_sigmaIPhiIPhi_isLoaded;
  bool photon_isEB_;
  TBranch *photon_isEB_branch;
  bool photon_isEB_isLoaded;
  bool photon_isEBEEGap_;
  TBranch *photon_isEBEEGap_branch;
  bool photon_isEBEEGap_isLoaded;
  bool photon_isEE_;
  TBranch *photon_isEE_branch;
  bool photon_isEE_isLoaded;
  bool photon_isGap_;
  TBranch *photon_isGap_branch;
  bool photon_isGap_isLoaded;
  bool photon_is_METSafe_;
  TBranch *photon_is_METSafe_branch;
  bool photon_is_METSafe_isLoaded;
  bool photon_is_PFID_;
  TBranch *photon_is_PFID_branch;
  bool photon_is_PFID_isLoaded;
  bool photon_is_beamHaloSafe_;
  TBranch *photon_is_beamHaloSafe_branch;
  bool photon_is_beamHaloSafe_isLoaded;
  bool photon_is_conversionSafe_;
  TBranch *photon_is_conversionSafe_branch;
  bool photon_is_conversionSafe_isLoaded;
  bool photon_is_genMatched_prompt_;
  TBranch *photon_is_genMatched_prompt_branch;
  bool photon_is_genMatched_prompt_isLoaded;
  bool photon_is_inTime_;
  TBranch *photon_is_inTime_branch;
  bool photon_is_inTime_isLoaded;
  bool photon_is_spikeSafe_;
  TBranch *photon_is_spikeSafe_branch;
  bool photon_is_spikeSafe_isLoaded;
  float photon_mass_;
  TBranch *photon_mass_branch;
  bool photon_mass_isLoaded;
  bool photon_pass_HGGSelection_;
  TBranch *photon_pass_HGGSelection_branch;
  bool photon_pass_HGGSelection_isLoaded;
  float photon_phi_;
  TBranch *photon_phi_branch;
  bool photon_phi_isLoaded;
  float photon_pt_;
  TBranch *photon_pt_branch;
  bool photon_pt_isLoaded;
  float photon_seedTime_;
  TBranch *photon_seedTime_branch;
  bool photon_seedTime_isLoaded;
public:
  void Init(TTree *tree);
  void GetEntry(unsigned int idx);
  void LoadAllBranches();
  const vector<float> &ak4jets_CEMF();
  const float &ak4jets_HT();
  const vector<float> &ak4jets_NEMF();
  const vector<unsigned char> &ak4jets_btagWP_Bits();
  const vector<float> &ak4jets_eta();
  const vector<bool> &ak4jets_is_genMatched();
  const vector<bool> &ak4jets_is_genMatched_fullCone();
  const vector<float> &ak4jets_mass();
  const vector<float> &ak4jets_phi();
  const vector<float> &ak4jets_pt();
  const vector<float> &ak8jets_eta();
  const vector<float> &ak8jets_mass();
  const vector<float> &ak8jets_phi();
  const vector<float> &ak8jets_pt();
  const float &dPhi_pTboson_pTmiss();
  const float &dPhi_pTbosonjets_pTmiss();
  const float &dilepton_eta();
  const int &dilepton_id();
  const float &dilepton_mass();
  const float &dilepton_phi();
  const float &dilepton_pt();
  const vector<float> &electrons_full5x5_r9();
  const vector<float> &electrons_full5x5_sigmaIEtaIEta();
  const vector<float> &electrons_full5x5_sigmaIPhiIPhi();
  const vector<float> &electrons_seedTime();
  const float &event_mTZZ();
  const float &event_mZZ();
  const float &event_mllg();
  const unsigned int &event_n_ak4jets_pt20();
  const unsigned int &event_n_ak4jets_pt20_btagged_loose();
  const unsigned int &event_n_ak4jets_pt20_btagged_medium();
  const unsigned int &event_n_ak4jets_pt30();
  const unsigned int &event_n_ak4jets_pt30_btagged_loose();
  const unsigned int &event_n_ak4jets_pt30_btagged_medium();
  const unsigned int &event_n_vtxs_good();
  const float &event_pTmiss();
  const bool &event_pass_tightMETFilters();
  const float &event_phimiss();
  const float &event_wgt();
  const float &event_wgt_SFs();
  const float &event_wgt_SFs_PUJetId();
  const float &event_wgt_SFs_btagging();
  const float &event_wgt_SFs_electrons();
  const float &event_wgt_SFs_muons();
  const float &event_wgt_SFs_photons();
  const float &event_wgt_adjustment_NNPDF30();
  const float &event_wgt_triggers();
  const float &event_wgt_triggers_Dilepton();
  const float &event_wgt_triggers_PFHT_Control();
  const float &event_wgt_triggers_SingleLepton();
  const float &event_wgt_triggers_SinglePhoton();
  const float &genmet_pTmiss();
  const float &genmet_phimiss();
  const vector<float> &leptons_eff();
  const vector<float> &leptons_eff_DF();
  const vector<float> &leptons_eta();
  const vector<int> &leptons_id();
  const vector<bool> &leptons_is_TOmatched_SingleLepton();
  const vector<bool> &leptons_is_genMatched_prompt();
  const vector<float> &leptons_mass();
  const vector<float> &leptons_phi();
  const vector<float> &leptons_pt();
  const float &min_abs_dPhi_pTj_pTmiss();
  const float &pConst_JJQCD_SIG_ghg2_1_JHUGen();
  const float &pConst_JJVBF_SIG_ghv1_1_JHUGen();
  const float &p_JJQCD_SIG_ghg2_1_JHUGen();
  const float &p_JJVBF_SIG_ghv1_1_JHUGen();
  const float &p_JJVBF_SIG_ghv1_1_ghv1prime2_1E4_JHUGen();
  const float &p_JJVBF_SIG_ghv1_1_ghv2_1_JHUGen();
  const float &p_JJVBF_SIG_ghv1_1_ghv4_1_JHUGen();
  const float &p_JJVBF_SIG_ghv1prime2_1E4_JHUGen();
  const float &p_JJVBF_SIG_ghv2_1_JHUGen();
  const float &p_JJVBF_SIG_ghv4_1_JHUGen();
  const float &p_JJVBF_SIG_ghza1prime2_1E4_JHUGen();
  const float &photon_MIPTotalEnergy();
  const float &photon_eta();
  const float &photon_full5x5_r9();
  const float &photon_full5x5_sigmaIEtaIEta();
  const float &photon_full5x5_sigmaIPhiIPhi();
  const bool &photon_isEB();
  const bool &photon_isEBEEGap();
  const bool &photon_isEE();
  const bool &photon_isGap();
  const bool &photon_is_METSafe();
  const bool &photon_is_PFID();
  const bool &photon_is_beamHaloSafe();
  const bool &photon_is_conversionSafe();
  const bool &photon_is_genMatched_prompt();
  const bool &photon_is_inTime();
  const bool &photon_is_spikeSafe();
  const float &photon_mass();
  const bool &photon_pass_HGGSelection();
  const float &photon_phi();
  const float &photon_pt();
  const float &photon_seedTime();
  static void progress( int nEventsTotal, int nEventsChain );
};

#ifndef __CINT__
extern SkimTree st;
#endif

namespace tas {

  const vector<float> &ak4jets_CEMF();
  const float &ak4jets_HT();
  const vector<float> &ak4jets_NEMF();
  const vector<unsigned char> &ak4jets_btagWP_Bits();
  const vector<float> &ak4jets_eta();
  const vector<bool> &ak4jets_is_genMatched();
  const vector<bool> &ak4jets_is_genMatched_fullCone();
  const vector<float> &ak4jets_mass();
  const vector<float> &ak4jets_phi();
  const vector<float> &ak4jets_pt();
  const vector<float> &ak8jets_eta();
  const vector<float> &ak8jets_mass();
  const vector<float> &ak8jets_phi();
  const vector<float> &ak8jets_pt();
  const float &dPhi_pTboson_pTmiss();
  const float &dPhi_pTbosonjets_pTmiss();
  const float &dilepton_eta();
  const int &dilepton_id();
  const float &dilepton_mass();
  const float &dilepton_phi();
  const float &dilepton_pt();
  const vector<float> &electrons_full5x5_r9();
  const vector<float> &electrons_full5x5_sigmaIEtaIEta();
  const vector<float> &electrons_full5x5_sigmaIPhiIPhi();
  const vector<float> &electrons_seedTime();
  const float &event_mTZZ();
  const float &event_mZZ();
  const float &event_mllg();
  const unsigned int &event_n_ak4jets_pt20();
  const unsigned int &event_n_ak4jets_pt20_btagged_loose();
  const unsigned int &event_n_ak4jets_pt20_btagged_medium();
  const unsigned int &event_n_ak4jets_pt30();
  const unsigned int &event_n_ak4jets_pt30_btagged_loose();
  const unsigned int &event_n_ak4jets_pt30_btagged_medium();
  const unsigned int &event_n_vtxs_good();
  const float &event_pTmiss();
  const bool &event_pass_tightMETFilters();
  const float &event_phimiss();
  const float &event_wgt();
  const float &event_wgt_SFs();
  const float &event_wgt_SFs_PUJetId();
  const float &event_wgt_SFs_btagging();
  const float &event_wgt_SFs_electrons();
  const float &event_wgt_SFs_muons();
  const float &event_wgt_SFs_photons();
  const float &event_wgt_adjustment_NNPDF30();
  const float &event_wgt_triggers();
  const float &event_wgt_triggers_Dilepton();
  const float &event_wgt_triggers_PFHT_Control();
  const float &event_wgt_triggers_SingleLepton();
  const float &event_wgt_triggers_SinglePhoton();
  const float &genmet_pTmiss();
  const float &genmet_phimiss();
  const vector<float> &leptons_eff();
  const vector<float> &leptons_eff_DF();
  const vector<float> &leptons_eta();
  const vector<int> &leptons_id();
  const vector<bool> &leptons_is_TOmatched_SingleLepton();
  const vector<bool> &leptons_is_genMatched_prompt();
  const vector<float> &leptons_mass();
  const vector<float> &leptons_phi();
  const vector<float> &leptons_pt();
  const float &min_abs_dPhi_pTj_pTmiss();
  const float &pConst_JJQCD_SIG_ghg2_1_JHUGen();
  const float &pConst_JJVBF_SIG_ghv1_1_JHUGen();
  const float &p_JJQCD_SIG_ghg2_1_JHUGen();
  const float &p_JJVBF_SIG_ghv1_1_JHUGen();
  const float &p_JJVBF_SIG_ghv1_1_ghv1prime2_1E4_JHUGen();
  const float &p_JJVBF_SIG_ghv1_1_ghv2_1_JHUGen();
  const float &p_JJVBF_SIG_ghv1_1_ghv4_1_JHUGen();
  const float &p_JJVBF_SIG_ghv1prime2_1E4_JHUGen();
  const float &p_JJVBF_SIG_ghv2_1_JHUGen();
  const float &p_JJVBF_SIG_ghv4_1_JHUGen();
  const float &p_JJVBF_SIG_ghza1prime2_1E4_JHUGen();
  const float &photon_MIPTotalEnergy();
  const float &photon_eta();
  const float &photon_full5x5_r9();
  const float &photon_full5x5_sigmaIEtaIEta();
  const float &photon_full5x5_sigmaIPhiIPhi();
  const bool &photon_isEB();
  const bool &photon_isEBEEGap();
  const bool &photon_isEE();
  const bool &photon_isGap();
  const bool &photon_is_METSafe();
  const bool &photon_is_PFID();
  const bool &photon_is_beamHaloSafe();
  const bool &photon_is_conversionSafe();
  const bool &photon_is_genMatched_prompt();
  const bool &photon_is_inTime();
  const bool &photon_is_spikeSafe();
  const float &photon_mass();
  const bool &photon_pass_HGGSelection();
  const float &photon_phi();
  const float &photon_pt();
  const float &photon_seedTime();
}
#endif
