// -*- C++ -*-
#ifndef SkimTree_H
#define SkimTree_H
#include "Math/LorentzVector.h"
#include "Math/GenVector/PtEtaPhiM4D.h"
#include "Math/Point3D.h"
#include "TMath.h"
#include "TBranch.h"
#include "TTree.h"
#include "TH1F.h"
#include "TFile.h"
#include "TBits.h"
#include <vector>
#include <unistd.h>
typedef ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<float> > LorentzVector;

// Generated with command: -t SkimTree -n tas -o st -c SkimTree /hadoop/cms/store/user/sicheng/Offshell_2L2Nu/Worker/output/DYestTest/SkimTrees/v2_10_fullsamp_2016/photon_2016B_2016_Nominal_0_of_1.root 

using namespace std;
class SkimTree {
private:
protected:
  unsigned int index;
  float pt_photon_;
  TBranch *pt_photon_branch;
  bool pt_photon_isLoaded;
  float chiso_photon_;
  TBranch *chiso_photon_branch;
  bool chiso_photon_isLoaded;
  bool id_photon_Hgg_;
  TBranch *id_photon_Hgg_branch;
  bool id_photon_Hgg_isLoaded;
  bool is_emu_;
  TBranch *is_emu_branch;
  bool is_emu_isLoaded;
  float mipE_photon_;
  TBranch *mipE_photon_branch;
  bool mipE_photon_isLoaded;
  float met_uncorr_phi_;
  TBranch *met_uncorr_phi_branch;
  bool met_uncorr_phi_isLoaded;
  float mZZ_;
  TBranch *mZZ_branch;
  bool mZZ_isLoaded;
  bool convveto_photon_;
  TBranch *convveto_photon_branch;
  bool convveto_photon_isLoaded;
  float dphi_boson_met_;
  TBranch *dphi_boson_met_branch;
  bool dphi_boson_met_isLoaded;
  float dphi_lljets20_met_;
  TBranch *dphi_lljets20_met_branch;
  bool dphi_lljets20_met_isLoaded;
  unsigned long long event_event_;
  TBranch *event_event_branch;
  bool event_event_isLoaded;
  float eta_jet2_;
  TBranch *eta_jet2_branch;
  bool eta_jet2_isLoaded;
  unsigned int event_run_;
  TBranch *event_run_branch;
  bool event_run_isLoaded;
  unsigned int event_Njets20_btagged_medium_;
  TBranch *event_Njets20_btagged_medium_branch;
  bool event_Njets20_btagged_medium_isLoaded;
  float pt_boson_;
  TBranch *pt_boson_branch;
  bool pt_boson_isLoaded;
  int id_track_;
  TBranch *id_track_branch;
  bool id_track_isLoaded;
  bool is_mumu_;
  TBranch *is_mumu_branch;
  bool is_mumu_isLoaded;
  float event_wgt_trig_muon_;
  TBranch *event_wgt_trig_muon_branch;
  bool event_wgt_trig_muon_isLoaded;
  float eta_photon_;
  TBranch *eta_photon_branch;
  bool eta_photon_isLoaded;
  bool is_VBFcat_;
  TBranch *is_VBFcat_branch;
  bool is_VBFcat_isLoaded;
  float event_wgt_pileup_;
  TBranch *event_wgt_pileup_branch;
  bool event_wgt_pileup_isLoaded;
  unsigned int event_Njets_btagged_medium_;
  TBranch *event_Njets_btagged_medium_branch;
  bool event_Njets_btagged_medium_isLoaded;
  unsigned int event_Njets20_btagged_loose_;
  TBranch *event_Njets20_btagged_loose_branch;
  bool event_Njets20_btagged_loose_isLoaded;
  float eta_track_;
  TBranch *eta_track_branch;
  bool eta_track_isLoaded;
  float pt_track_;
  TBranch *pt_track_branch;
  bool pt_track_isLoaded;
  float eta_jet1_;
  TBranch *eta_jet1_branch;
  bool eta_jet1_isLoaded;
  float event_wgt_;
  TBranch *event_wgt_branch;
  bool event_wgt_isLoaded;
  bool pass_trackveto_;
  TBranch *pass_trackveto_branch;
  bool pass_trackveto_isLoaded;
  bool is_ee_;
  TBranch *is_ee_branch;
  bool is_ee_isLoaded;
  float mass_boson_;
  TBranch *mass_boson_branch;
  bool mass_boson_isLoaded;
  float phi_boson_;
  TBranch *phi_boson_branch;
  bool phi_boson_isLoaded;
  bool has_photons_inHEM1516_;
  TBranch *has_photons_inHEM1516_branch;
  bool has_photons_inHEM1516_isLoaded;
  float mTZZ_;
  TBranch *mTZZ_branch;
  bool mTZZ_isLoaded;
  float eta_l1_;
  TBranch *eta_l1_branch;
  bool eta_l1_isLoaded;
  bool has_ak4jets_inHEM1516_;
  TBranch *has_ak4jets_inHEM1516_branch;
  bool has_ak4jets_inHEM1516_isLoaded;
  int id_l1_;
  TBranch *id_l1_branch;
  bool id_l1_isLoaded;
  float seedtime_photon_;
  TBranch *seedtime_photon_branch;
  bool seedtime_photon_isLoaded;
  float pt_jet2_;
  TBranch *pt_jet2_branch;
  bool pt_jet2_isLoaded;
  float sipip_photon_;
  TBranch *sipip_photon_branch;
  bool sipip_photon_isLoaded;
  bool pass_lepveto_;
  TBranch *pass_lepveto_branch;
  bool pass_lepveto_isLoaded;
  float phi_jet1_;
  TBranch *phi_jet1_branch;
  bool phi_jet1_isLoaded;
  float sieie_photon_;
  TBranch *sieie_photon_branch;
  bool sieie_photon_isLoaded;
  bool is_gamma_;
  TBranch *is_gamma_branch;
  bool is_gamma_isLoaded;
  float nhiso_photon_;
  TBranch *nhiso_photon_branch;
  bool nhiso_photon_isLoaded;
  bool isEB_photon_;
  TBranch *isEB_photon_branch;
  bool isEB_photon_isLoaded;
  bool has_electrons_inHEM1516_;
  TBranch *has_electrons_inHEM1516_branch;
  bool has_electrons_inHEM1516_isLoaded;
  int id_l2_;
  TBranch *id_l2_branch;
  bool id_l2_isLoaded;
  float event_wgt_OSSF_triggers_;
  TBranch *event_wgt_OSSF_triggers_branch;
  bool event_wgt_OSSF_triggers_isLoaded;
  float eta_boson_;
  TBranch *eta_boson_branch;
  bool eta_boson_isLoaded;
  float phi_photon_;
  TBranch *phi_photon_branch;
  bool phi_photon_isLoaded;
  float event_DjjVBF_;
  TBranch *event_DjjVBF_branch;
  bool event_DjjVBF_isLoaded;
  unsigned int event_Njets_;
  TBranch *event_Njets_branch;
  bool event_Njets_isLoaded;
  float event_DjjVBF_rl_;
  TBranch *event_DjjVBF_rl_branch;
  bool event_DjjVBF_rl_isLoaded;
  float pfiso_photon_;
  TBranch *pfiso_photon_branch;
  bool pfiso_photon_isLoaded;
  unsigned int event_Njets20_;
  TBranch *event_Njets20_branch;
  bool event_Njets20_isLoaded;
  float event_wgt_trig_electron_;
  TBranch *event_wgt_trig_electron_branch;
  bool event_wgt_trig_electron_isLoaded;
  float genmet_pt_;
  TBranch *genmet_pt_branch;
  bool genmet_pt_isLoaded;
  float r9_photon_;
  TBranch *r9_photon_branch;
  bool r9_photon_isLoaded;
  float phi_l2_;
  TBranch *phi_l2_branch;
  bool phi_l2_isLoaded;
  float event_wgt_L1prefire_;
  TBranch *event_wgt_L1prefire_branch;
  bool event_wgt_L1prefire_isLoaded;
  unsigned int event_Nphotons_;
  TBranch *event_Nphotons_branch;
  bool event_Nphotons_isLoaded;
  float phi_l1_;
  TBranch *phi_l1_branch;
  bool phi_l1_isLoaded;
  float event_wgt_trig_photon_;
  TBranch *event_wgt_trig_photon_branch;
  bool event_wgt_trig_photon_isLoaded;
  float dphi_jet20_met_;
  TBranch *dphi_jet20_met_branch;
  bool dphi_jet20_met_isLoaded;
  float mindphi_jet_met_;
  TBranch *mindphi_jet_met_branch;
  bool mindphi_jet_met_isLoaded;
  float pt_l2_;
  TBranch *pt_l2_branch;
  bool pt_l2_isLoaded;
  float genmet_phi_;
  TBranch *genmet_phi_branch;
  bool genmet_phi_isLoaded;
  float pt_l1_;
  TBranch *pt_l1_branch;
  bool pt_l1_isLoaded;
  unsigned int event_nvtxs_good_;
  TBranch *event_nvtxs_good_branch;
  bool event_nvtxs_good_isLoaded;
  float e4oe1_photon_;
  TBranch *e4oe1_photon_branch;
  bool e4oe1_photon_isLoaded;
  float phi_track_;
  TBranch *phi_track_branch;
  bool phi_track_isLoaded;
  float dphi_lljets_met_;
  TBranch *dphi_lljets_met_branch;
  bool dphi_lljets_met_isLoaded;
  float pTmiss_;
  TBranch *pTmiss_branch;
  bool pTmiss_isLoaded;
  float met_uncorr_pt_;
  TBranch *met_uncorr_pt_branch;
  bool met_uncorr_pt_isLoaded;
  float pt_jet1_;
  TBranch *pt_jet1_branch;
  bool pt_jet1_isLoaded;
  unsigned int event_lumi_;
  TBranch *event_lumi_branch;
  bool event_lumi_isLoaded;
  float eta_l2_;
  TBranch *eta_l2_branch;
  bool eta_l2_isLoaded;
  float phi_jet2_;
  TBranch *phi_jet2_branch;
  bool phi_jet2_isLoaded;
  float event_wgt_OSDF_triggers_;
  TBranch *event_wgt_OSDF_triggers_branch;
  bool event_wgt_OSDF_triggers_isLoaded;
  float phimiss_;
  TBranch *phimiss_branch;
  bool phimiss_isLoaded;
  unsigned int event_HT_;
  TBranch *event_HT_branch;
  bool event_HT_isLoaded;
  float event_wgt_SFs_;
  TBranch *event_wgt_SFs_branch;
  bool event_wgt_SFs_isLoaded;
  unsigned int event_Njets_btagged_;
  TBranch *event_Njets_btagged_branch;
  bool event_Njets_btagged_isLoaded;
public:
  void Init(TTree *tree);
  void GetEntry(unsigned int idx);
  void LoadAllBranches();
  const float &pt_photon();
  const float &chiso_photon();
  const bool &id_photon_Hgg();
  const bool &is_emu();
  const float &mipE_photon();
  const float &met_uncorr_phi();
  const float &mZZ();
  const bool &convveto_photon();
  const float &dphi_boson_met();
  const float &dphi_lljets20_met();
  const unsigned long long &event_event();
  const float &eta_jet2();
  const unsigned int &event_run();
  const unsigned int &event_Njets20_btagged_medium();
  const float &pt_boson();
  const int &id_track();
  const bool &is_mumu();
  const float &event_wgt_trig_muon();
  const float &eta_photon();
  const bool &is_VBFcat();
  const float &event_wgt_pileup();
  const unsigned int &event_Njets_btagged_medium();
  const unsigned int &event_Njets20_btagged_loose();
  const float &eta_track();
  const float &pt_track();
  const float &eta_jet1();
  const float &event_wgt();
  const bool &pass_trackveto();
  const bool &is_ee();
  const float &mass_boson();
  const float &phi_boson();
  const bool &has_photons_inHEM1516();
  const float &mTZZ();
  const float &eta_l1();
  const bool &has_ak4jets_inHEM1516();
  const int &id_l1();
  const float &seedtime_photon();
  const float &pt_jet2();
  const float &sipip_photon();
  const bool &pass_lepveto();
  const float &phi_jet1();
  const float &sieie_photon();
  const bool &is_gamma();
  const float &nhiso_photon();
  const bool &isEB_photon();
  const bool &has_electrons_inHEM1516();
  const int &id_l2();
  const float &event_wgt_OSSF_triggers();
  const float &eta_boson();
  const float &phi_photon();
  const float &event_DjjVBF();
  const unsigned int &event_Njets();
  const float &event_DjjVBF_rl();
  const float &pfiso_photon();
  const unsigned int &event_Njets20();
  const float &event_wgt_trig_electron();
  const float &genmet_pt();
  const float &r9_photon();
  const float &phi_l2();
  const float &event_wgt_L1prefire();
  const unsigned int &event_Nphotons();
  const float &phi_l1();
  const float &event_wgt_trig_photon();
  const float &dphi_jet20_met();
  const float &mindphi_jet_met();
  const float &pt_l2();
  const float &genmet_phi();
  const float &pt_l1();
  const unsigned int &event_nvtxs_good();
  const float &e4oe1_photon();
  const float &phi_track();
  const float &dphi_lljets_met();
  const float &pTmiss();
  const float &met_uncorr_pt();
  const float &pt_jet1();
  const unsigned int &event_lumi();
  const float &eta_l2();
  const float &phi_jet2();
  const float &event_wgt_OSDF_triggers();
  const float &phimiss();
  const unsigned int &event_HT();
  const float &event_wgt_SFs();
  const unsigned int &event_Njets_btagged();
  static void progress( int nEventsTotal, int nEventsChain );
};

#ifndef __CINT__
extern SkimTree st;
#endif

namespace tas {

  const float &pt_photon();
  const float &chiso_photon();
  const bool &id_photon_Hgg();
  const bool &is_emu();
  const float &mipE_photon();
  const float &met_uncorr_phi();
  const float &mZZ();
  const bool &convveto_photon();
  const float &dphi_boson_met();
  const float &dphi_lljets20_met();
  const unsigned long long &event_event();
  const float &eta_jet2();
  const unsigned int &event_run();
  const unsigned int &event_Njets20_btagged_medium();
  const float &pt_boson();
  const int &id_track();
  const bool &is_mumu();
  const float &event_wgt_trig_muon();
  const float &eta_photon();
  const bool &is_VBFcat();
  const float &event_wgt_pileup();
  const unsigned int &event_Njets_btagged_medium();
  const unsigned int &event_Njets20_btagged_loose();
  const float &eta_track();
  const float &pt_track();
  const float &eta_jet1();
  const float &event_wgt();
  const bool &pass_trackveto();
  const bool &is_ee();
  const float &mass_boson();
  const float &phi_boson();
  const bool &has_photons_inHEM1516();
  const float &mTZZ();
  const float &eta_l1();
  const bool &has_ak4jets_inHEM1516();
  const int &id_l1();
  const float &seedtime_photon();
  const float &pt_jet2();
  const float &sipip_photon();
  const bool &pass_lepveto();
  const float &phi_jet1();
  const float &sieie_photon();
  const bool &is_gamma();
  const float &nhiso_photon();
  const bool &isEB_photon();
  const bool &has_electrons_inHEM1516();
  const int &id_l2();
  const float &event_wgt_OSSF_triggers();
  const float &eta_boson();
  const float &phi_photon();
  const float &event_DjjVBF();
  const unsigned int &event_Njets();
  const float &event_DjjVBF_rl();
  const float &pfiso_photon();
  const unsigned int &event_Njets20();
  const float &event_wgt_trig_electron();
  const float &genmet_pt();
  const float &r9_photon();
  const float &phi_l2();
  const float &event_wgt_L1prefire();
  const unsigned int &event_Nphotons();
  const float &phi_l1();
  const float &event_wgt_trig_photon();
  const float &dphi_jet20_met();
  const float &mindphi_jet_met();
  const float &pt_l2();
  const float &genmet_phi();
  const float &pt_l1();
  const unsigned int &event_nvtxs_good();
  const float &e4oe1_photon();
  const float &phi_track();
  const float &dphi_lljets_met();
  const float &pTmiss();
  const float &met_uncorr_pt();
  const float &pt_jet1();
  const unsigned int &event_lumi();
  const float &eta_l2();
  const float &phi_jet2();
  const float &event_wgt_OSDF_triggers();
  const float &phimiss();
  const unsigned int &event_HT();
  const float &event_wgt_SFs();
  const unsigned int &event_Njets_btagged();
}
#endif
