// -*- C++ -*-
#ifndef TriLepTree_H
#define TriLepTree_H
#include "Math/LorentzVector.h"
#include "Math/GenVector/PtEtaPhiM4D.h"
#include "Math/Point3D.h"
#include "TMath.h"
#include "TBranch.h"
#include "TTree.h"
#include "TH1F.h"
#include "TFile.h"
#include "TBits.h"
#include <vector>
#include <unistd.h>
typedef ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<float> > LorentzVector;

// Generated with command: -t SkimTree -n tas -o st -c TriLepTree -plv /hadoop/cms/store/user/usarica/Offshell_2L2Nu/Worker/output/3LEvents/SkimTrees/210315/AK4Jets_WithPUJetId_NoTightLeptonJetId_ParticleCleaned/PFMET_WithXY_NoJER_WithPartMomCorr_P4Preserved_ResolutionCorrected/2016/WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8_RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v1_Nominal_0_of_4.root 

using namespace std;
class TriLepTree {
private:
protected:
  unsigned int index;
  float KFactor_EW_NLO_qqVV_Bkg_EWDn_;
  TBranch *KFactor_EW_NLO_qqVV_Bkg_EWDn_branch;
  bool KFactor_EW_NLO_qqVV_Bkg_EWDn_isLoaded;
  float KFactor_EW_NLO_qqVV_Bkg_EWUp_;
  TBranch *KFactor_EW_NLO_qqVV_Bkg_EWUp_branch;
  bool KFactor_EW_NLO_qqVV_Bkg_EWUp_isLoaded;
  float KFactor_EW_NLO_qqVV_Bkg_Nominal_;
  TBranch *KFactor_EW_NLO_qqVV_Bkg_Nominal_branch;
  bool KFactor_EW_NLO_qqVV_Bkg_Nominal_isLoaded;
  float KFactor_EW_NLO_qqVV_Bkg_arg_mass_;
  TBranch *KFactor_EW_NLO_qqVV_Bkg_arg_mass_branch;
  bool KFactor_EW_NLO_qqVV_Bkg_arg_mass_isLoaded;
  float KFactor_EW_NLO_qqVV_Bkg_arg_pthat_;
  TBranch *KFactor_EW_NLO_qqVV_Bkg_arg_pthat_branch;
  bool KFactor_EW_NLO_qqVV_Bkg_arg_pthat_isLoaded;
  float KFactor_EW_NLO_qqVV_Bkg_arg_rho_;
  TBranch *KFactor_EW_NLO_qqVV_Bkg_arg_rho_branch;
  bool KFactor_EW_NLO_qqVV_Bkg_arg_rho_isLoaded;
  float KFactor_EW_NLO_qqVV_Bkg_arg_that_;
  TBranch *KFactor_EW_NLO_qqVV_Bkg_arg_that_branch;
  bool KFactor_EW_NLO_qqVV_Bkg_arg_that_isLoaded;
  float KFactor_QCD_NNLO_qqVV_Bkg_Nominal_;
  TBranch *KFactor_QCD_NNLO_qqVV_Bkg_Nominal_branch;
  bool KFactor_QCD_NNLO_qqVV_Bkg_Nominal_isLoaded;
  float KFactor_QCD_NNLO_qqVV_Bkg_arg_mass_;
  TBranch *KFactor_QCD_NNLO_qqVV_Bkg_arg_mass_branch;
  bool KFactor_QCD_NNLO_qqVV_Bkg_arg_mass_isLoaded;
  float KFactor_QCD_NNLO_qqVV_Bkg_arg_pthat_;
  TBranch *KFactor_QCD_NNLO_qqVV_Bkg_arg_pthat_branch;
  bool KFactor_QCD_NNLO_qqVV_Bkg_arg_pthat_isLoaded;
  vector<float> *ak4jets_CEMF_;
  TBranch *ak4jets_CEMF_branch;
  bool ak4jets_CEMF_isLoaded;
  float ak4jets_HT_;
  TBranch *ak4jets_HT_branch;
  bool ak4jets_HT_isLoaded;
  float ak4jets_MHT_;
  TBranch *ak4jets_MHT_branch;
  bool ak4jets_MHT_isLoaded;
  vector<float> *ak4jets_NEMF_;
  TBranch *ak4jets_NEMF_branch;
  bool ak4jets_NEMF_isLoaded;
  vector<unsigned char> *ak4jets_btagWP_Bits_;
  TBranch *ak4jets_btagWP_Bits_branch;
  bool ak4jets_btagWP_Bits_isLoaded;
  vector<float> *ak4jets_eta_;
  TBranch *ak4jets_eta_branch;
  bool ak4jets_eta_isLoaded;
  vector<bool> *ak4jets_is_genMatched_;
  TBranch *ak4jets_is_genMatched_branch;
  bool ak4jets_is_genMatched_isLoaded;
  vector<bool> *ak4jets_is_genMatched_fullCone_;
  TBranch *ak4jets_is_genMatched_fullCone_branch;
  bool ak4jets_is_genMatched_fullCone_isLoaded;
  vector<float> *ak4jets_mass_;
  TBranch *ak4jets_mass_branch;
  bool ak4jets_mass_isLoaded;
  vector<float> *ak4jets_phi_;
  TBranch *ak4jets_phi_branch;
  bool ak4jets_phi_isLoaded;
  vector<float> *ak4jets_pt_;
  TBranch *ak4jets_pt_branch;
  bool ak4jets_pt_isLoaded;
  vector<float> *ak8jets_eta_;
  TBranch *ak8jets_eta_branch;
  bool ak8jets_eta_isLoaded;
  vector<float> *ak8jets_mass_;
  TBranch *ak8jets_mass_branch;
  bool ak8jets_mass_isLoaded;
  vector<float> *ak8jets_phi_;
  TBranch *ak8jets_phi_branch;
  bool ak8jets_phi_isLoaded;
  vector<float> *ak8jets_pt_;
  TBranch *ak8jets_pt_branch;
  bool ak8jets_pt_isLoaded;
  float dPhi_Z_W_;
  TBranch *dPhi_Z_W_branch;
  bool dPhi_Z_W_isLoaded;
  float dPhi_lepW_pTmiss_;
  TBranch *dPhi_lepW_pTmiss_branch;
  bool dPhi_lepW_pTmiss_isLoaded;
  float dPhi_pTleptonsjets_pTmiss_;
  TBranch *dPhi_pTleptonsjets_pTmiss_branch;
  bool dPhi_pTleptonsjets_pTmiss_isLoaded;
  vector<unsigned short> *dilepton_daughter_indices_;
  TBranch *dilepton_daughter_indices_branch;
  bool dilepton_daughter_indices_isLoaded;
  float dilepton_eta_;
  TBranch *dilepton_eta_branch;
  bool dilepton_eta_isLoaded;
  int dilepton_id_;
  TBranch *dilepton_id_branch;
  bool dilepton_id_isLoaded;
  float dilepton_mass_;
  TBranch *dilepton_mass_branch;
  bool dilepton_mass_isLoaded;
  float dilepton_phi_;
  TBranch *dilepton_phi_branch;
  bool dilepton_phi_isLoaded;
  float dilepton_pt_;
  TBranch *dilepton_pt_branch;
  bool dilepton_pt_isLoaded;
  vector<bool> *electrons_conv_vtx_flag_;
  TBranch *electrons_conv_vtx_flag_branch;
  bool electrons_conv_vtx_flag_isLoaded;
  vector<float> *electrons_full5x5_r9_;
  TBranch *electrons_full5x5_r9_branch;
  bool electrons_full5x5_r9_isLoaded;
  vector<float> *electrons_full5x5_sigmaIEtaIEta_;
  TBranch *electrons_full5x5_sigmaIEtaIEta_branch;
  bool electrons_full5x5_sigmaIEtaIEta_isLoaded;
  vector<float> *electrons_full5x5_sigmaIPhiIPhi_;
  TBranch *electrons_full5x5_sigmaIPhiIPhi_branch;
  bool electrons_full5x5_sigmaIPhiIPhi_isLoaded;
  vector<unsigned short> *electrons_n_all_missing_inner_hits_;
  TBranch *electrons_n_all_missing_inner_hits_branch;
  bool electrons_n_all_missing_inner_hits_isLoaded;
  vector<unsigned short> *electrons_n_missing_inner_hits_;
  TBranch *electrons_n_missing_inner_hits_branch;
  bool electrons_n_missing_inner_hits_isLoaded;
  vector<bool> *electrons_pass_tightCharge_;
  TBranch *electrons_pass_tightCharge_branch;
  bool electrons_pass_tightCharge_isLoaded;
  vector<float> *electrons_seedTime_;
  TBranch *electrons_seedTime_branch;
  bool electrons_seedTime_isLoaded;
  float event_m3l_;
  TBranch *event_m3l_branch;
  bool event_m3l_isLoaded;
  float event_mTl_;
  TBranch *event_mTl_branch;
  bool event_mTl_isLoaded;
  float event_mWVis_;
  TBranch *event_mWVis_branch;
  bool event_mWVis_isLoaded;
  unsigned int event_n_ak4jets_pt20_;
  TBranch *event_n_ak4jets_pt20_branch;
  bool event_n_ak4jets_pt20_isLoaded;
  unsigned int event_n_ak4jets_pt20_btagged_loose_;
  TBranch *event_n_ak4jets_pt20_btagged_loose_branch;
  bool event_n_ak4jets_pt20_btagged_loose_isLoaded;
  unsigned int event_n_ak4jets_pt20_btagged_medium_;
  TBranch *event_n_ak4jets_pt20_btagged_medium_branch;
  bool event_n_ak4jets_pt20_btagged_medium_isLoaded;
  unsigned int event_n_ak4jets_pt30_;
  TBranch *event_n_ak4jets_pt30_branch;
  bool event_n_ak4jets_pt30_isLoaded;
  unsigned int event_n_ak4jets_pt30_btagged_loose_;
  TBranch *event_n_ak4jets_pt30_btagged_loose_branch;
  bool event_n_ak4jets_pt30_btagged_loose_isLoaded;
  unsigned int event_n_ak4jets_pt30_btagged_medium_;
  TBranch *event_n_ak4jets_pt30_btagged_medium_branch;
  bool event_n_ak4jets_pt30_btagged_medium_isLoaded;
  unsigned int event_n_leptons_fakeableBase_;
  TBranch *event_n_leptons_fakeableBase_branch;
  bool event_n_leptons_fakeableBase_isLoaded;
  unsigned int event_n_vtxs_good_;
  TBranch *event_n_vtxs_good_branch;
  bool event_n_vtxs_good_isLoaded;
  float event_pTmiss_;
  TBranch *event_pTmiss_branch;
  bool event_pTmiss_isLoaded;
  bool event_pass_tightMETFilters_;
  TBranch *event_pass_tightMETFilters_branch;
  bool event_pass_tightMETFilters_isLoaded;
  float event_phimiss_;
  TBranch *event_phimiss_branch;
  bool event_phimiss_isLoaded;
  float event_wgt_;
  TBranch *event_wgt_branch;
  bool event_wgt_isLoaded;
  float event_wgt_L1PrefiringDn_;
  TBranch *event_wgt_L1PrefiringDn_branch;
  bool event_wgt_L1PrefiringDn_isLoaded;
  float event_wgt_L1PrefiringUp_;
  TBranch *event_wgt_L1PrefiringUp_branch;
  bool event_wgt_L1PrefiringUp_isLoaded;
  float event_wgt_PUDn_;
  TBranch *event_wgt_PUDn_branch;
  bool event_wgt_PUDn_isLoaded;
  float event_wgt_PUUp_;
  TBranch *event_wgt_PUUp_branch;
  bool event_wgt_PUUp_isLoaded;
  float event_wgt_SFs_PUJetId_;
  TBranch *event_wgt_SFs_PUJetId_branch;
  bool event_wgt_SFs_PUJetId_isLoaded;
  float event_wgt_SFs_PUJetId_EffDn_;
  TBranch *event_wgt_SFs_PUJetId_EffDn_branch;
  bool event_wgt_SFs_PUJetId_EffDn_isLoaded;
  float event_wgt_SFs_PUJetId_EffUp_;
  TBranch *event_wgt_SFs_PUJetId_EffUp_branch;
  bool event_wgt_SFs_PUJetId_EffUp_isLoaded;
  float event_wgt_SFs_btagging_;
  TBranch *event_wgt_SFs_btagging_branch;
  bool event_wgt_SFs_btagging_isLoaded;
  float event_wgt_SFs_btagging_EffDn_;
  TBranch *event_wgt_SFs_btagging_EffDn_branch;
  bool event_wgt_SFs_btagging_EffDn_isLoaded;
  float event_wgt_SFs_btagging_EffUp_;
  TBranch *event_wgt_SFs_btagging_EffUp_branch;
  bool event_wgt_SFs_btagging_EffUp_isLoaded;
  float event_wgt_SFs_electrons_;
  TBranch *event_wgt_SFs_electrons_branch;
  bool event_wgt_SFs_electrons_isLoaded;
  float event_wgt_SFs_electrons_AltMCDn_;
  TBranch *event_wgt_SFs_electrons_AltMCDn_branch;
  bool event_wgt_SFs_electrons_AltMCDn_isLoaded;
  float event_wgt_SFs_electrons_AltMCUp_;
  TBranch *event_wgt_SFs_electrons_AltMCUp_branch;
  bool event_wgt_SFs_electrons_AltMCUp_isLoaded;
  float event_wgt_SFs_electrons_StatDn_;
  TBranch *event_wgt_SFs_electrons_StatDn_branch;
  bool event_wgt_SFs_electrons_StatDn_isLoaded;
  float event_wgt_SFs_electrons_StatUp_;
  TBranch *event_wgt_SFs_electrons_StatUp_branch;
  bool event_wgt_SFs_electrons_StatUp_isLoaded;
  float event_wgt_SFs_electrons_SystDn_;
  TBranch *event_wgt_SFs_electrons_SystDn_branch;
  bool event_wgt_SFs_electrons_SystDn_isLoaded;
  float event_wgt_SFs_electrons_SystUp_;
  TBranch *event_wgt_SFs_electrons_SystUp_branch;
  bool event_wgt_SFs_electrons_SystUp_isLoaded;
  float event_wgt_SFs_muons_;
  TBranch *event_wgt_SFs_muons_branch;
  bool event_wgt_SFs_muons_isLoaded;
  float event_wgt_SFs_muons_AltMCDn_;
  TBranch *event_wgt_SFs_muons_AltMCDn_branch;
  bool event_wgt_SFs_muons_AltMCDn_isLoaded;
  float event_wgt_SFs_muons_AltMCUp_;
  TBranch *event_wgt_SFs_muons_AltMCUp_branch;
  bool event_wgt_SFs_muons_AltMCUp_isLoaded;
  float event_wgt_SFs_muons_StatDn_;
  TBranch *event_wgt_SFs_muons_StatDn_branch;
  bool event_wgt_SFs_muons_StatDn_isLoaded;
  float event_wgt_SFs_muons_StatUp_;
  TBranch *event_wgt_SFs_muons_StatUp_branch;
  bool event_wgt_SFs_muons_StatUp_isLoaded;
  float event_wgt_SFs_muons_SystDn_;
  TBranch *event_wgt_SFs_muons_SystDn_branch;
  bool event_wgt_SFs_muons_SystDn_isLoaded;
  float event_wgt_SFs_muons_SystUp_;
  TBranch *event_wgt_SFs_muons_SystUp_branch;
  bool event_wgt_SFs_muons_SystUp_isLoaded;
  float event_wgt_SFs_photons_;
  TBranch *event_wgt_SFs_photons_branch;
  bool event_wgt_SFs_photons_isLoaded;
  float event_wgt_SFs_photons_EffDn_;
  TBranch *event_wgt_SFs_photons_EffDn_branch;
  bool event_wgt_SFs_photons_EffDn_isLoaded;
  float event_wgt_SFs_photons_EffUp_;
  TBranch *event_wgt_SFs_photons_EffUp_branch;
  bool event_wgt_SFs_photons_EffUp_isLoaded;
  float event_wgt_adjustment_AsMZDn_;
  TBranch *event_wgt_adjustment_AsMZDn_branch;
  bool event_wgt_adjustment_AsMZDn_isLoaded;
  float event_wgt_adjustment_AsMZUp_;
  TBranch *event_wgt_adjustment_AsMZUp_branch;
  bool event_wgt_adjustment_AsMZUp_isLoaded;
  float event_wgt_adjustment_NNPDF30_;
  TBranch *event_wgt_adjustment_NNPDF30_branch;
  bool event_wgt_adjustment_NNPDF30_isLoaded;
  float event_wgt_adjustment_NNPDF30_AsMZDn_;
  TBranch *event_wgt_adjustment_NNPDF30_AsMZDn_branch;
  bool event_wgt_adjustment_NNPDF30_AsMZDn_isLoaded;
  float event_wgt_adjustment_NNPDF30_AsMZUp_;
  TBranch *event_wgt_adjustment_NNPDF30_AsMZUp_branch;
  bool event_wgt_adjustment_NNPDF30_AsMZUp_isLoaded;
  float event_wgt_adjustment_NNPDF30_PDFReplicaDn_;
  TBranch *event_wgt_adjustment_NNPDF30_PDFReplicaDn_branch;
  bool event_wgt_adjustment_NNPDF30_PDFReplicaDn_isLoaded;
  float event_wgt_adjustment_NNPDF30_PDFReplicaUp_;
  TBranch *event_wgt_adjustment_NNPDF30_PDFReplicaUp_branch;
  bool event_wgt_adjustment_NNPDF30_PDFReplicaUp_isLoaded;
  float event_wgt_adjustment_PDFReplicaDn_;
  TBranch *event_wgt_adjustment_PDFReplicaDn_branch;
  bool event_wgt_adjustment_PDFReplicaDn_isLoaded;
  float event_wgt_adjustment_PDFReplicaUp_;
  TBranch *event_wgt_adjustment_PDFReplicaUp_branch;
  bool event_wgt_adjustment_PDFReplicaUp_isLoaded;
  float event_wgt_adjustment_PDFScaleDn_;
  TBranch *event_wgt_adjustment_PDFScaleDn_branch;
  bool event_wgt_adjustment_PDFScaleDn_isLoaded;
  float event_wgt_adjustment_PDFScaleUp_;
  TBranch *event_wgt_adjustment_PDFScaleUp_branch;
  bool event_wgt_adjustment_PDFScaleUp_isLoaded;
  float event_wgt_adjustment_PythiaScaleDn_;
  TBranch *event_wgt_adjustment_PythiaScaleDn_branch;
  bool event_wgt_adjustment_PythiaScaleDn_isLoaded;
  float event_wgt_adjustment_PythiaScaleUp_;
  TBranch *event_wgt_adjustment_PythiaScaleUp_branch;
  bool event_wgt_adjustment_PythiaScaleUp_isLoaded;
  float event_wgt_adjustment_QCDScaleDn_;
  TBranch *event_wgt_adjustment_QCDScaleDn_branch;
  bool event_wgt_adjustment_QCDScaleDn_isLoaded;
  float event_wgt_adjustment_QCDScaleUp_;
  TBranch *event_wgt_adjustment_QCDScaleUp_branch;
  bool event_wgt_adjustment_QCDScaleUp_isLoaded;
  vector<float> *event_wgt_triggers_Dilepton_DF_;
  TBranch *event_wgt_triggers_Dilepton_DF_branch;
  bool event_wgt_triggers_Dilepton_DF_isLoaded;
  vector<float> *event_wgt_triggers_Dilepton_DF_Extra_;
  TBranch *event_wgt_triggers_Dilepton_DF_Extra_branch;
  bool event_wgt_triggers_Dilepton_DF_Extra_isLoaded;
  vector<float> *event_wgt_triggers_Dilepton_SF_;
  TBranch *event_wgt_triggers_Dilepton_SF_branch;
  bool event_wgt_triggers_Dilepton_SF_isLoaded;
  vector<float> *event_wgt_triggers_SingleLepton_;
  TBranch *event_wgt_triggers_SingleLepton_branch;
  bool event_wgt_triggers_SingleLepton_isLoaded;
  float event_wgt_triggers_Trilepton_;
  TBranch *event_wgt_triggers_Trilepton_branch;
  bool event_wgt_triggers_Trilepton_isLoaded;
  vector<float> *genak4jets_eta_;
  TBranch *genak4jets_eta_branch;
  bool genak4jets_eta_isLoaded;
  vector<float> *genak4jets_mass_;
  TBranch *genak4jets_mass_branch;
  bool genak4jets_mass_isLoaded;
  vector<float> *genak4jets_phi_;
  TBranch *genak4jets_phi_branch;
  bool genak4jets_phi_isLoaded;
  vector<float> *genak4jets_pt_;
  TBranch *genak4jets_pt_branch;
  bool genak4jets_pt_isLoaded;
  float genmet_pTmiss_;
  TBranch *genmet_pTmiss_branch;
  bool genmet_pTmiss_isLoaded;
  float genmet_phimiss_;
  TBranch *genmet_phimiss_branch;
  bool genmet_phimiss_isLoaded;
  float genpromptparticles_sump4_mass_;
  TBranch *genpromptparticles_sump4_mass_branch;
  bool genpromptparticles_sump4_mass_isLoaded;
  float genpromptparticles_sump4_pt_;
  TBranch *genpromptparticles_sump4_pt_branch;
  bool genpromptparticles_sump4_pt_isLoaded;
  float genpromptparticles_sump4_rapidity_;
  TBranch *genpromptparticles_sump4_rapidity_branch;
  bool genpromptparticles_sump4_rapidity_isLoaded;
  vector<float> *leptons_eff_;
  TBranch *leptons_eff_branch;
  bool leptons_eff_isLoaded;
  vector<float> *leptons_eff_DF_;
  TBranch *leptons_eff_DF_branch;
  bool leptons_eff_DF_isLoaded;
  vector<float> *leptons_eff_DF_StatDn_;
  TBranch *leptons_eff_DF_StatDn_branch;
  bool leptons_eff_DF_StatDn_isLoaded;
  vector<float> *leptons_eff_DF_StatUp_;
  TBranch *leptons_eff_DF_StatUp_branch;
  bool leptons_eff_DF_StatUp_isLoaded;
  vector<float> *leptons_eff_DF_SystDn_;
  TBranch *leptons_eff_DF_SystDn_branch;
  bool leptons_eff_DF_SystDn_isLoaded;
  vector<float> *leptons_eff_DF_SystUp_;
  TBranch *leptons_eff_DF_SystUp_branch;
  bool leptons_eff_DF_SystUp_isLoaded;
  vector<float> *leptons_eff_StatDn_;
  TBranch *leptons_eff_StatDn_branch;
  bool leptons_eff_StatDn_isLoaded;
  vector<float> *leptons_eff_StatUp_;
  TBranch *leptons_eff_StatUp_branch;
  bool leptons_eff_StatUp_isLoaded;
  vector<float> *leptons_eff_SystDn_;
  TBranch *leptons_eff_SystDn_branch;
  bool leptons_eff_SystDn_isLoaded;
  vector<float> *leptons_eff_SystUp_;
  TBranch *leptons_eff_SystUp_branch;
  bool leptons_eff_SystUp_isLoaded;
  vector<float> *leptons_eta_;
  TBranch *leptons_eta_branch;
  bool leptons_eta_isLoaded;
  vector<int> *leptons_id_;
  TBranch *leptons_id_branch;
  bool leptons_id_isLoaded;
  vector<bool> *leptons_is_fakeableBase_;
  TBranch *leptons_is_fakeableBase_branch;
  bool leptons_is_fakeableBase_isLoaded;
  vector<bool> *leptons_is_genMatched_prompt_;
  TBranch *leptons_is_genMatched_prompt_branch;
  bool leptons_is_genMatched_prompt_isLoaded;
  vector<float> *leptons_mass_;
  TBranch *leptons_mass_branch;
  bool leptons_mass_isLoaded;
  vector<vector<bool> > *leptons_pass_fakeable_ids_;
  TBranch *leptons_pass_fakeable_ids_branch;
  bool leptons_pass_fakeable_ids_isLoaded;
  vector<float> *leptons_phi_;
  TBranch *leptons_phi_branch;
  bool leptons_phi_isLoaded;
  vector<float> *leptons_pt_;
  TBranch *leptons_pt_branch;
  bool leptons_pt_isLoaded;
  vector<float> *leptons_relIso_;
  TBranch *leptons_relIso_branch;
  bool leptons_relIso_isLoaded;
  float min_abs_dPhi_pTj_pTmiss_;
  TBranch *min_abs_dPhi_pTj_pTmiss_branch;
  bool min_abs_dPhi_pTj_pTmiss_isLoaded;
public:
  void Init(TTree *tree);
  void GetEntry(unsigned int idx);
  void LoadAllBranches();
  const float &KFactor_EW_NLO_qqVV_Bkg_EWDn();
  const float &KFactor_EW_NLO_qqVV_Bkg_EWUp();
  const float &KFactor_EW_NLO_qqVV_Bkg_Nominal();
  const float &KFactor_EW_NLO_qqVV_Bkg_arg_mass();
  const float &KFactor_EW_NLO_qqVV_Bkg_arg_pthat();
  const float &KFactor_EW_NLO_qqVV_Bkg_arg_rho();
  const float &KFactor_EW_NLO_qqVV_Bkg_arg_that();
  const float &KFactor_QCD_NNLO_qqVV_Bkg_Nominal();
  const float &KFactor_QCD_NNLO_qqVV_Bkg_arg_mass();
  const float &KFactor_QCD_NNLO_qqVV_Bkg_arg_pthat();
  const vector<float> &ak4jets_CEMF();
  const float &ak4jets_HT();
  const float &ak4jets_MHT();
  const vector<float> &ak4jets_NEMF();
  const vector<unsigned char> &ak4jets_btagWP_Bits();
  const vector<float> &ak4jets_eta();
  const vector<bool> &ak4jets_is_genMatched();
  const vector<bool> &ak4jets_is_genMatched_fullCone();
  const vector<float> &ak4jets_mass();
  const vector<float> &ak4jets_phi();
  const vector<float> &ak4jets_pt();
  const vector<float> &ak8jets_eta();
  const vector<float> &ak8jets_mass();
  const vector<float> &ak8jets_phi();
  const vector<float> &ak8jets_pt();
  const float &dPhi_Z_W();
  const float &dPhi_lepW_pTmiss();
  const float &dPhi_pTleptonsjets_pTmiss();
  const vector<unsigned short> &dilepton_daughter_indices();
  const float &dilepton_eta();
  const int &dilepton_id();
  const float &dilepton_mass();
  const float &dilepton_phi();
  const float &dilepton_pt();
  const vector<bool> &electrons_conv_vtx_flag();
  const vector<float> &electrons_full5x5_r9();
  const vector<float> &electrons_full5x5_sigmaIEtaIEta();
  const vector<float> &electrons_full5x5_sigmaIPhiIPhi();
  const vector<unsigned short> &electrons_n_all_missing_inner_hits();
  const vector<unsigned short> &electrons_n_missing_inner_hits();
  const vector<bool> &electrons_pass_tightCharge();
  const vector<float> &electrons_seedTime();
  const float &event_m3l();
  const float &event_mTl();
  const float &event_mWVis();
  const unsigned int &event_n_ak4jets_pt20();
  const unsigned int &event_n_ak4jets_pt20_btagged_loose();
  const unsigned int &event_n_ak4jets_pt20_btagged_medium();
  const unsigned int &event_n_ak4jets_pt30();
  const unsigned int &event_n_ak4jets_pt30_btagged_loose();
  const unsigned int &event_n_ak4jets_pt30_btagged_medium();
  const unsigned int &event_n_leptons_fakeableBase();
  const unsigned int &event_n_vtxs_good();
  const float &event_pTmiss();
  const bool &event_pass_tightMETFilters();
  const float &event_phimiss();
  const float &event_wgt();
  const float &event_wgt_L1PrefiringDn();
  const float &event_wgt_L1PrefiringUp();
  const float &event_wgt_PUDn();
  const float &event_wgt_PUUp();
  const float &event_wgt_SFs_PUJetId();
  const float &event_wgt_SFs_PUJetId_EffDn();
  const float &event_wgt_SFs_PUJetId_EffUp();
  const float &event_wgt_SFs_btagging();
  const float &event_wgt_SFs_btagging_EffDn();
  const float &event_wgt_SFs_btagging_EffUp();
  const float &event_wgt_SFs_electrons();
  const float &event_wgt_SFs_electrons_AltMCDn();
  const float &event_wgt_SFs_electrons_AltMCUp();
  const float &event_wgt_SFs_electrons_StatDn();
  const float &event_wgt_SFs_electrons_StatUp();
  const float &event_wgt_SFs_electrons_SystDn();
  const float &event_wgt_SFs_electrons_SystUp();
  const float &event_wgt_SFs_muons();
  const float &event_wgt_SFs_muons_AltMCDn();
  const float &event_wgt_SFs_muons_AltMCUp();
  const float &event_wgt_SFs_muons_StatDn();
  const float &event_wgt_SFs_muons_StatUp();
  const float &event_wgt_SFs_muons_SystDn();
  const float &event_wgt_SFs_muons_SystUp();
  const float &event_wgt_SFs_photons();
  const float &event_wgt_SFs_photons_EffDn();
  const float &event_wgt_SFs_photons_EffUp();
  const float &event_wgt_adjustment_AsMZDn();
  const float &event_wgt_adjustment_AsMZUp();
  const float &event_wgt_adjustment_NNPDF30();
  const float &event_wgt_adjustment_NNPDF30_AsMZDn();
  const float &event_wgt_adjustment_NNPDF30_AsMZUp();
  const float &event_wgt_adjustment_NNPDF30_PDFReplicaDn();
  const float &event_wgt_adjustment_NNPDF30_PDFReplicaUp();
  const float &event_wgt_adjustment_PDFReplicaDn();
  const float &event_wgt_adjustment_PDFReplicaUp();
  const float &event_wgt_adjustment_PDFScaleDn();
  const float &event_wgt_adjustment_PDFScaleUp();
  const float &event_wgt_adjustment_PythiaScaleDn();
  const float &event_wgt_adjustment_PythiaScaleUp();
  const float &event_wgt_adjustment_QCDScaleDn();
  const float &event_wgt_adjustment_QCDScaleUp();
  const vector<float> &event_wgt_triggers_Dilepton_DF();
  const vector<float> &event_wgt_triggers_Dilepton_DF_Extra();
  const vector<float> &event_wgt_triggers_Dilepton_SF();
  const vector<float> &event_wgt_triggers_SingleLepton();
  const float &event_wgt_triggers_Trilepton();
  const vector<float> &genak4jets_eta();
  const vector<float> &genak4jets_mass();
  const vector<float> &genak4jets_phi();
  const vector<float> &genak4jets_pt();
  const float &genmet_pTmiss();
  const float &genmet_phimiss();
  const float &genpromptparticles_sump4_mass();
  const float &genpromptparticles_sump4_pt();
  const float &genpromptparticles_sump4_rapidity();
  const vector<float> &leptons_eff();
  const vector<float> &leptons_eff_DF();
  const vector<float> &leptons_eff_DF_StatDn();
  const vector<float> &leptons_eff_DF_StatUp();
  const vector<float> &leptons_eff_DF_SystDn();
  const vector<float> &leptons_eff_DF_SystUp();
  const vector<float> &leptons_eff_StatDn();
  const vector<float> &leptons_eff_StatUp();
  const vector<float> &leptons_eff_SystDn();
  const vector<float> &leptons_eff_SystUp();
  const vector<float> &leptons_eta();
  const vector<int> &leptons_id();
  const vector<bool> &leptons_is_fakeableBase();
  const vector<bool> &leptons_is_genMatched_prompt();
  const vector<float> &leptons_mass();
  const vector<vector<bool> > &leptons_pass_fakeable_ids();
  const vector<float> &leptons_phi();
  const vector<float> &leptons_pt();
  const vector<float> &leptons_relIso();
  const float &min_abs_dPhi_pTj_pTmiss();
  static void progress( int nEventsTotal, int nEventsChain );
};

#ifndef __CINT__
extern TriLepTree st;
#endif

namespace tas {

  const float &KFactor_EW_NLO_qqVV_Bkg_EWDn();
  const float &KFactor_EW_NLO_qqVV_Bkg_EWUp();
  const float &KFactor_EW_NLO_qqVV_Bkg_Nominal();
  const float &KFactor_EW_NLO_qqVV_Bkg_arg_mass();
  const float &KFactor_EW_NLO_qqVV_Bkg_arg_pthat();
  const float &KFactor_EW_NLO_qqVV_Bkg_arg_rho();
  const float &KFactor_EW_NLO_qqVV_Bkg_arg_that();
  const float &KFactor_QCD_NNLO_qqVV_Bkg_Nominal();
  const float &KFactor_QCD_NNLO_qqVV_Bkg_arg_mass();
  const float &KFactor_QCD_NNLO_qqVV_Bkg_arg_pthat();
  const vector<float> &ak4jets_CEMF();
  const float &ak4jets_HT();
  const float &ak4jets_MHT();
  const vector<float> &ak4jets_NEMF();
  const vector<unsigned char> &ak4jets_btagWP_Bits();
  const vector<float> &ak4jets_eta();
  const vector<bool> &ak4jets_is_genMatched();
  const vector<bool> &ak4jets_is_genMatched_fullCone();
  const vector<float> &ak4jets_mass();
  const vector<float> &ak4jets_phi();
  const vector<float> &ak4jets_pt();
  const vector<float> &ak8jets_eta();
  const vector<float> &ak8jets_mass();
  const vector<float> &ak8jets_phi();
  const vector<float> &ak8jets_pt();
  const float &dPhi_Z_W();
  const float &dPhi_lepW_pTmiss();
  const float &dPhi_pTleptonsjets_pTmiss();
  const vector<unsigned short> &dilepton_daughter_indices();
  const float &dilepton_eta();
  const int &dilepton_id();
  const float &dilepton_mass();
  const float &dilepton_phi();
  const float &dilepton_pt();
  const vector<bool> &electrons_conv_vtx_flag();
  const vector<float> &electrons_full5x5_r9();
  const vector<float> &electrons_full5x5_sigmaIEtaIEta();
  const vector<float> &electrons_full5x5_sigmaIPhiIPhi();
  const vector<unsigned short> &electrons_n_all_missing_inner_hits();
  const vector<unsigned short> &electrons_n_missing_inner_hits();
  const vector<bool> &electrons_pass_tightCharge();
  const vector<float> &electrons_seedTime();
  const float &event_m3l();
  const float &event_mTl();
  const float &event_mWVis();
  const unsigned int &event_n_ak4jets_pt20();
  const unsigned int &event_n_ak4jets_pt20_btagged_loose();
  const unsigned int &event_n_ak4jets_pt20_btagged_medium();
  const unsigned int &event_n_ak4jets_pt30();
  const unsigned int &event_n_ak4jets_pt30_btagged_loose();
  const unsigned int &event_n_ak4jets_pt30_btagged_medium();
  const unsigned int &event_n_leptons_fakeableBase();
  const unsigned int &event_n_vtxs_good();
  const float &event_pTmiss();
  const bool &event_pass_tightMETFilters();
  const float &event_phimiss();
  const float &event_wgt();
  const float &event_wgt_L1PrefiringDn();
  const float &event_wgt_L1PrefiringUp();
  const float &event_wgt_PUDn();
  const float &event_wgt_PUUp();
  const float &event_wgt_SFs_PUJetId();
  const float &event_wgt_SFs_PUJetId_EffDn();
  const float &event_wgt_SFs_PUJetId_EffUp();
  const float &event_wgt_SFs_btagging();
  const float &event_wgt_SFs_btagging_EffDn();
  const float &event_wgt_SFs_btagging_EffUp();
  const float &event_wgt_SFs_electrons();
  const float &event_wgt_SFs_electrons_AltMCDn();
  const float &event_wgt_SFs_electrons_AltMCUp();
  const float &event_wgt_SFs_electrons_StatDn();
  const float &event_wgt_SFs_electrons_StatUp();
  const float &event_wgt_SFs_electrons_SystDn();
  const float &event_wgt_SFs_electrons_SystUp();
  const float &event_wgt_SFs_muons();
  const float &event_wgt_SFs_muons_AltMCDn();
  const float &event_wgt_SFs_muons_AltMCUp();
  const float &event_wgt_SFs_muons_StatDn();
  const float &event_wgt_SFs_muons_StatUp();
  const float &event_wgt_SFs_muons_SystDn();
  const float &event_wgt_SFs_muons_SystUp();
  const float &event_wgt_SFs_photons();
  const float &event_wgt_SFs_photons_EffDn();
  const float &event_wgt_SFs_photons_EffUp();
  const float &event_wgt_adjustment_AsMZDn();
  const float &event_wgt_adjustment_AsMZUp();
  const float &event_wgt_adjustment_NNPDF30();
  const float &event_wgt_adjustment_NNPDF30_AsMZDn();
  const float &event_wgt_adjustment_NNPDF30_AsMZUp();
  const float &event_wgt_adjustment_NNPDF30_PDFReplicaDn();
  const float &event_wgt_adjustment_NNPDF30_PDFReplicaUp();
  const float &event_wgt_adjustment_PDFReplicaDn();
  const float &event_wgt_adjustment_PDFReplicaUp();
  const float &event_wgt_adjustment_PDFScaleDn();
  const float &event_wgt_adjustment_PDFScaleUp();
  const float &event_wgt_adjustment_PythiaScaleDn();
  const float &event_wgt_adjustment_PythiaScaleUp();
  const float &event_wgt_adjustment_QCDScaleDn();
  const float &event_wgt_adjustment_QCDScaleUp();
  const vector<float> &event_wgt_triggers_Dilepton_DF();
  const vector<float> &event_wgt_triggers_Dilepton_DF_Extra();
  const vector<float> &event_wgt_triggers_Dilepton_SF();
  const vector<float> &event_wgt_triggers_SingleLepton();
  const float &event_wgt_triggers_Trilepton();
  const vector<float> &genak4jets_eta();
  const vector<float> &genak4jets_mass();
  const vector<float> &genak4jets_phi();
  const vector<float> &genak4jets_pt();
  const float &genmet_pTmiss();
  const float &genmet_phimiss();
  const float &genpromptparticles_sump4_mass();
  const float &genpromptparticles_sump4_pt();
  const float &genpromptparticles_sump4_rapidity();
  const vector<float> &leptons_eff();
  const vector<float> &leptons_eff_DF();
  const vector<float> &leptons_eff_DF_StatDn();
  const vector<float> &leptons_eff_DF_StatUp();
  const vector<float> &leptons_eff_DF_SystDn();
  const vector<float> &leptons_eff_DF_SystUp();
  const vector<float> &leptons_eff_StatDn();
  const vector<float> &leptons_eff_StatUp();
  const vector<float> &leptons_eff_SystDn();
  const vector<float> &leptons_eff_SystUp();
  const vector<float> &leptons_eta();
  const vector<int> &leptons_id();
  const vector<bool> &leptons_is_fakeableBase();
  const vector<bool> &leptons_is_genMatched_prompt();
  const vector<float> &leptons_mass();
  const vector<vector<bool> > &leptons_pass_fakeable_ids();
  const vector<float> &leptons_phi();
  const vector<float> &leptons_pt();
  const vector<float> &leptons_relIso();
  const float &min_abs_dPhi_pTj_pTmiss();
}
#endif
